### ISSUE TITLE
Could not be set since 0.1.0

### ISSUE THREAD

**Issue by collateral87** [t0bst4r/hacs-conversation_chain#3]
This integration is great, but since v0.1.0 this component could not be set/load anymore:

![Screenshot_20240218_035135_Home Assistant](https://github.com/t0bst4r/hacs-conversation_chain/assets/97076257/f768565d-0d72-49ea-83fb-909c67ef03a2)

**Comment by t0bst4r** [comment]
Thanks for this hint. I didn‘t thought there is already an user, actually 😄 
It seems to be an easy fix, I will do that later today.

**Comment by tbrasser** [comment]
Also interested in using this to fallback to OpenAI (Y)

**Comment by t0bst4r** [comment]
@collateral87 
I fixed it in the new release. HACS will find it during its next scan. This is typically done every 30 minutes.
Unfortunately you need to re-create your agent integration. Just delete the old one and create a new.

@tbrasser 
feel free to start using this integration.

since this was my first release, the process was a big buggy and a broken version was released. with version 0.1.1 it is fixed now.

**Comment by t0bst4r** [comment]
@collateral87 
One more thing: I renamed the repo from `hass-conversation_chain` to `hacs-conversation_chain`. GitHub will redirect this for some time, but not forever. So you should replace the repo in your HACS config.
